analytics: {}
color:
  brandColors:
    - '#210e0f'
    - '#e7effc'
    - '#854842'
    - '#7d833d'
    - '#fa883e'
  brandStrength: 0.5
  lightness: 0.125
  rhythmicContrast: 1
  saturation: 0.3125
cta: {}
layout_spectrum: 0.875
name: Verhalenverteller Bastiaan
opengraph: {}
purpose: []
typography_spectrum: 0.45001
