name: Bastiaan
favicon: null
layout_spectrum: 0.50748
typography_spectrum: 0.45001
title: Bastiaan de Zwitser
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#210e0f'
    - '#e7effc'
    - '#854842'
    - '#7d833d'
    - '#fa883e'
  brandStrength: 0.5
  lightness: 0.02272207522764802
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
