name: Bastiaan
favicon: null
layout_spectrum: 0.08391941827721894
typography_spectrum: 0.46492208004929125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5073622532654554
  lightness: 0.02272207522764802
  saturation: 0.31019385857507586
  rhythmicContrast: 0.9376180174294859
purpose: []
